<style scoped lang="scss">
  .login-cont{
    .page-title{
      margin: 40px 0 20px 10px;
    }
    .page-body {
      box-shadow: 0px 4px 16px rgba(185, 185, 185, 0.25);
      padding: 30px 30px;
      min-height: 350px;
      .code-cont{
        text-align: justify;
        line-height: 1.45;
        background-color: #ffffff;
        padding: 0 16px;
        .copy-icon{
          top: 12px;
          right: 12px;
        }
        pre{
          code{
            color: #24292e;
            font-family: monospace,monospace!important;
            white-space: pre-line;
          }
        }
      }
    }
  }
</style>

<template>
	<div class="login-cont">
    <p class="page-title ft-blue-1 ft-size-20">Privacy Policy</p>
    <div class="page-body bg-neutral-white border-radius-6">
      <div class="code-cont border-radius-4 relative">
      Welcome to the privacy policy of alue.org website (hereinafter referred to as the “Website”). The Website will be operated and administered by its owning company ‘Mawdoo3 Ltd” and/or any of its subsidiaries.
      <!-- <br/><br/> -->
      <h4>Preamble</h4> 
This privacy policy informs you of our policies regarding the collection, use and disclosure of personal data when you use our Website and the choices you have associated with that data by this privacy policy our utmost concern to maintain and guarantee the privacy of your usage of this Website and the information provided by your side on the Website.
<br><br>We use your personal data -as defined hereunder- to provide and improve the service of the Website (the “Services”) and /or your usage of the Website. By using the Service and/or the Website, you agree to the collection and use of information in accordance with this policy.
<h4>Definitions</h4>
Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions of Service:
<br><br>Personal Data means data of user of the Website provided upon the user’s usage of the Website either in our possession or likely to come into our possession) including but not limited to Usage Data.
<br><br>Usage Data is data collected automatically either generated by the use of the Website or from the Service infrastructure itself (for example, the duration of a page visit).
<br><br>Cookies are small files stored on your device (computer or mobile device).
<br><br>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.
<br><br>Data Processors (or Service Providers) mean any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of third parties (including but not limited to various Service Providers selected solely by us) in order to process your data more effectively.
<br><br>Data Subject (or User) is any living individual who is using our Service and/or the Website and is the subject of Personal Data.

<h4>Information Collection and Use</h4>
 
We collect several different types of information and data for various purposes to provide and improve our Service on the Website to you. Types of data collected include but are not limited to:
<ul>
<li>Email address</li>
<li>First name and last name</li>
<li>Phone number</li>
<li>Address, State, Province, ZIP/Postal code, City</li>
<li>Cookies and Usage Data</li>
</ul>
We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information of whatever type that may be of interest to you whether developed by us solely or by third parties or in cooperating between us and any third party.    

<h4>Usage Data</h4>
We may also collect information that your browser sends whenever you use the Website or when you access the Website by or through a mobile device (“Usage Data”).
<br><br>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Website that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
<br><br>When you access the Website with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.

<h4>Location Data</h4>
We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.
<br><br>You can activate or deactivate the Location Data services upon using the Services through the settings of your device.

<h4>Tracking Cookies Data</h4>
We use cookies and similar tracking technologies to track the activity on our Website and we hold certain information.
<br><br>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
<br><br>You can set your browser to reject cookies or to limit and to indicate to the process of sending cookies.
<br><br>By disabling cookies, some contents or features of the Website may not function properly or may not be shown correctly.


<h4>Use of Data</h4>
We use the collected data for various purposes, which include but are not limited to:
<ul>
<li>To provide and maintain our Service.</li>
<li>To notify you about changes to our Service.</li>
<li>To allow you to participate in interactive features of our Service when you choose to do so.</li>
<li>To provide customer support.</li>
<li>To gather analysis or valuable information so that we can improve our Service and/or the Website.</li>
<li>To monitor the usage of our Service and/or the Website.</li>
<li>To detect, prevent and address technical issues.</li>
<li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have unsubscribed to such services</li>
</ul>

<h4>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</h4>
If you are from the European Economic Area (EEA), the legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
<br><br>We may process your Personal Data because:
<ul>
<li>We need to perform a contract with you.</li>
<li>You have given us permission to do so.</li>
<li>The processing is in our legitimate interests and it is not overridden by your rights.</li>
<li>For payment processing purposes.</li>
<li>To comply with the law.</li>
</ul>

If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us. You have the following data protection rights:
<ul>
<li>The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
<li>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
<li>The right to object. You have the right to object to our processing of your Personal Data.</li>
<li>The right of restriction. You have the right to request that we restrict the processing of your personal information.</li>
<li>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
<li>The right to withdraw consent. You also have the right to withdraw your consent at any time where we have relied on your consent to process your personal information.</li>
</ul>
Please note that we may ask you to verify your identity before responding to such requests.
<br><br>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).

<h4>Retention of Data</h4>
We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.
<br><br>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service and/or the Website, or we are legally obligated to retain this data for longer periods.

<h4>Transfer of Data</h4>
Your information, including Personal Data, may be transferred to – and maintained on – computers  and other devices located outside of your geographical jurisdiction or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
<br><br>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to transfer your data to any other country where any of our affiliates and/or subsidiaries are located.
<br><br>We will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information


<h4>Legal Disclosure of Data </h4>
Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
<br>We may disclose your Personal Data in the good faith belief that such action is necessary to:
<ul>
<li>To comply with a legal obligation.</li>
<li>To protect and defend the rights or property of Mawdoo3 Ltd or any of its affiliates and/or subsidiaries.</li>
<li>To prevent or investigate possible wrongdoing in connection with the Website.</li>
<li>To protect the personal safety of users of the Website or the public.</li>
<li>To protect against legal liability.</li>
</ul>


<h4>Security of Data</h4>
The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security as some events may occur beyond our control and not be attributable to an action of willful misconduct and/or intentional negligence from our side.


<h4>Service Providers</h4>
We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide the Service on our behalf, perform Service-related services or assist us in analyzing how our Service is used.
<br><br>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.

<h4>Advertising</h4>
We may use third party Service Providers (including but not limited to AdMob by Google and Google AdSense DoubleClick Cookie) to show advertisements to you to help support and maintain our Service and/or the Website.

<h4>Behavioral Remarketing</h4>
We use remarketing services to advertise on third party websites to you after you visited our Website. We and our third party vendors (including but not limited to Twitter, Facebook and Google ADs) use cookies to inform, optimize and serve ads based on your past visits to our Website.

<h4>Payments</h4>
We may provide paid products and/or services within the Website. In that case, we use third party services for payment processing (e.g. payment processors).
<br><br>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their privacy policy.

<h4>Links to Other Sites</h4>
Our Website may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the privacy policy of every site you visit.
<br><br>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

<h4>Changes to This Privacy Policy</h4>
We may update and/or amend our Privacy Policy from time to time without notice. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this Website.

<h4>Contact Us</h4>

If you have any questions about this Privacy Policy, please contact us at hello@alue.org.
      </div>
    </div>
  </div>
</template>

<script>
  import Vue from "vue";

  export default {
    name: "privacy_policy",
    mounted() {
      
    },
    data() {
    	return {
   
    	};
    },
    methods: {

    }
  };
</script>
